relativeURLs: true
baseURL: https://satadru97.github.io/satadru.dev
languageCode: en-us
title: Satadru Mallick
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
disqusShortname: satadru-dev
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

#Menus:
  #main:
    #- identifier: blog
    #  name: Blog
    #  title: Blog posts
    #  url: /blogs
    #  weight: 1
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Satadru Mallick"
  description: Welcome to satadru.dev!
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"
  
  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Satadru."
    subtitle: "I build things for the web"
    content: "A passionate web app developer. I tend to make use of modern web technologies to build websites that looks great, feels fantastic, and functions correctly."
    image: /images/me.png
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "https://drive.google.com/file/d/1qoYXWD2JpczFFkiYQEKBUT3is6cmOeSq/view?usp=sharing"
      download: true
      newPage: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/satadru97/
        - icon: fab fa-github
          url: https://github.com/satadru97
      customIcons:
        - icon: /fav.png
          url: "https://satadru.dev"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.png"
    content: |-
      I am a software developer with a passion for web development. I have a background in computer science, and I have a strong interest in the intersection of technology and art. I am currently working as a software developer at [S🙴P Global](https://www.spglobal.com/en/) in India. 

      I am currently working on a project that will be used to help people find the best way to get around the city.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - C#
        - NET, .NET Core MVC, Web API
        - SQL
        - JavaScript, HTML, CSS
        - React, Redux, Jest
        - Node.js.

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Engineer II, Software Development"
        company: "S🙴P Global"
        companyUrl: "https://www.spglobal.com/en/"
        date: "September 2023 - present"
        content: |
          - Developed applications for the delivery and presentation of financial data, enhancing accessibility and user experience.
          - Addressed CSP Inline issues and integrated Azure AD in the .NET UI, leading Test Automation initiatives resulting in 30% decrease in manual testing efforts.
          - Implemented ETL Task using internal tools for financial report rectification based on ES Native Query, reducing processing time by 40%.
          - Improved SonarQube unit test code coverage for Node.js API from 50% to 80% using Jest, ensuring a more resilient codebase and minimizing post-release issues.
          - Leveraged Git and Bitbucket for version control, and Jira for Agile project management, ensuring efficient collaboration and task tracking.

      - job: "Systems Engineer"
        company: "Tata Consultancy Services Limited"
        companyUrl: "https://www.tcs.com/"
        date: "July 2019 - September 2023"
        content: |
          - Contributed significantly to development of new features for major US Banking Client, resulting in a increase in customer satisfaction.
          - Successfully migrated 4 modules of an existing web application from ASP.NET Web Forms + ASMX web service to React and REST Web API, resulting in a 30% improvement in performance and scalability.
          - Developed reusable UI components using React and implemented data flow using Redux, reducing development time by 25%.
          - Created and consumed REST APIs using C# ASP.NET, facilitating seamless data exchange and integration across systems.
          - Streamlined the fees calculation and approval process workflow by integrating configurable XML rules processed within .NET, improving efficiency and accuracy.
          - Practiced Test-Driven Development and conducted comprehensive unit testing with Jest, ensuring code reliability and robustness.
          - Conducted thorough code reviews and provided constructive feedback to team members, fostering a culture of continuous improvement and knowledge sharing.
          - Demonstrated excellent communication skills by effectively conveying technical concepts to non-technical stakeholders and team members.
          - Received recognition through various awards, including Star of The Month, Service & Commitment, Best Team, On the Spot, and Special Achievement Awards, for outstanding contributions and commitment to excellence.

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Bachelor of Technology in Computer Science & Engineering"
        school:
          name: "Academy of Technology (WBUT)"
          url: "https://aot.edu.in/"
        date: "August 2015 - May 2019"
        GPA: "8.5 out of 10.0"
        content: |-
          Represented in Smart India Hackathon Finale hosted by MHRD
      - title: "12th in Science"
        school:
          name: "Barajaguli Gopal Academy (WBCHSE)"
          url: "https://school.banglarshiksha.gov.in/ws/website/index/19102801202"
        date: "August 2013 - May 2015"
        GPA: "84.8%"
      - title: "10th"
        school:
          name: "Barajaguli Gopal Academy (WBBSE)"
          url: "https://school.banglarshiksha.gov.in/ws/website/index/19102801202"
        date: "August 2012 - May 2013"
        GPA: "92.57%"


  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
    btnName: Email
    btnLink: mailto:mallick@satadru.dev
    formspree:
      enable: true 
      formId: mqkrgvyo 
      emailCaption: "Your email"
      messageCaption: "Your message"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/satadru97
      linkedin: https://www.linkedin.com/in/satadru97/
      instagram: https://www.instagram.com/yipyip_97/
      facebook: https://www.facebook.com/satadru97

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "January 2, 2006"
    articleList: "January 2, 2006"
    articleRecent: "January 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
